// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/protolog/base.proto

package protolog

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Context struct {
	Request              *Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Meta                 []*Meta  `protobuf:"bytes,2,rep,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Context) Reset()         { *m = Context{} }
func (m *Context) String() string { return proto.CompactTextString(m) }
func (*Context) ProtoMessage()    {}
func (*Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_0058b2fb581006bc, []int{0}
}

func (m *Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context.Unmarshal(m, b)
}
func (m *Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context.Marshal(b, m, deterministic)
}
func (m *Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context.Merge(m, src)
}
func (m *Context) XXX_Size() int {
	return xxx_messageInfo_Context.Size(m)
}
func (m *Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Context proto.InternalMessageInfo

func (m *Context) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Context) GetMeta() []*Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type Request struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Rpcservice           string   `protobuf:"bytes,3,opt,name=rpcservice,proto3" json:"rpcservice,omitempty"`
	Rpcpackage           string   `protobuf:"bytes,4,opt,name=rpcpackage,proto3" json:"rpcpackage,omitempty"`
	Rpcmethod            string   `protobuf:"bytes,5,opt,name=rpcmethod,proto3" json:"rpcmethod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_0058b2fb581006bc, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Request) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Request) GetRpcservice() string {
	if m != nil {
		return m.Rpcservice
	}
	return ""
}

func (m *Request) GetRpcpackage() string {
	if m != nil {
		return m.Rpcpackage
	}
	return ""
}

func (m *Request) GetRpcmethod() string {
	if m != nil {
		return m.Rpcmethod
	}
	return ""
}

type Meta struct {
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Since this is non-typed, will never be indexed.
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_0058b2fb581006bc, []int{2}
}

func (m *Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meta.Unmarshal(m, b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
}
func (m *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(m, src)
}
func (m *Meta) XXX_Size() int {
	return xxx_messageInfo_Meta.Size(m)
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

func (m *Meta) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Meta) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Context)(nil), "protologs.proto.protolog.Context")
	proto.RegisterType((*Request)(nil), "protologs.proto.protolog.Request")
	proto.RegisterType((*Meta)(nil), "protologs.proto.protolog.Meta")
}

func init() { proto.RegisterFile("proto/protolog/base.proto", fileDescriptor_0058b2fb581006bc) }

var fileDescriptor_0058b2fb581006bc = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0xbf, 0x6a, 0xf3, 0x30,
	0x14, 0xc5, 0xf1, 0x9f, 0xc4, 0xf8, 0x06, 0x3e, 0x3e, 0x44, 0x29, 0x2a, 0x84, 0x90, 0x7a, 0xca,
	0xa4, 0x80, 0x3b, 0x74, 0xe8, 0xe6, 0xce, 0x85, 0xe0, 0xb1, 0x9b, 0x2c, 0x5f, 0x52, 0x93, 0xb8,
	0x52, 0x25, 0x39, 0xb4, 0x7d, 0x89, 0xbe, 0x72, 0xb1, 0x2c, 0xb5, 0x5d, 0xbc, 0x88, 0x7b, 0x7e,
	0xe7, 0x1e, 0xe9, 0x08, 0x6e, 0x94, 0x96, 0x56, 0xee, 0xdd, 0x79, 0x96, 0xc7, 0x7d, 0xc3, 0x0d,
	0x32, 0xa7, 0x08, 0x0d, 0xd0, 0x4c, 0x80, 0x05, 0x5d, 0x7c, 0x42, 0xf6, 0x28, 0x5f, 0x2d, 0xbe,
	0x5b, 0xf2, 0x00, 0x99, 0xc6, 0xb7, 0x01, 0x8d, 0xa5, 0xd1, 0x36, 0xda, 0xad, 0xca, 0x5b, 0x36,
	0x17, 0x63, 0xf5, 0xb4, 0x58, 0x87, 0x04, 0x29, 0x21, 0xed, 0xd1, 0x72, 0x1a, 0x6f, 0x93, 0xdd,
	0xaa, 0xdc, 0xcc, 0x27, 0x9f, 0xd0, 0xf2, 0xda, 0xed, 0x16, 0x5f, 0x11, 0x64, 0xfe, 0x22, 0xf2,
	0x0f, 0xe2, 0xae, 0x75, 0xef, 0xe6, 0x75, 0xdc, 0xb5, 0xe4, 0x1a, 0x96, 0x46, 0x0e, 0x5a, 0x20,
	0x8d, 0x1d, 0xf3, 0x8a, 0x6c, 0x00, 0xb4, 0x12, 0x06, 0xf5, 0xa5, 0x13, 0x48, 0x13, 0xe7, 0xfd,
	0x21, 0xde, 0x57, 0x5c, 0x9c, 0xf8, 0x11, 0x69, 0xfa, 0xe3, 0x7b, 0x42, 0xd6, 0x90, 0x6b, 0x25,
	0x7a, 0xb4, 0x2f, 0xb2, 0xa5, 0x0b, 0x67, 0xff, 0x82, 0x82, 0x41, 0x3a, 0xf6, 0x23, 0xff, 0x21,
	0x39, 0xe1, 0x87, 0xaf, 0x33, 0x8e, 0xe4, 0x0a, 0x16, 0x17, 0x7e, 0x1e, 0x42, 0x9d, 0x49, 0x54,
	0xf7, 0xb0, 0x16, 0xb2, 0x9f, 0xfd, 0x6c, 0x95, 0x57, 0xdc, 0xe0, 0x61, 0x54, 0x87, 0xe8, 0x19,
	0x02, 0x56, 0x4d, 0xb3, 0x74, 0xf3, 0xdd, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xca, 0xfd, 0x48,
	0xd5, 0xb4, 0x01, 0x00, 0x00,
}
