// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/protolog/paymentsvc.proto

package protolog

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PaymentSvcLog struct {
	PaymentId            string   `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	CustomerId           string   `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Method               string   `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	OrderId              string   `protobuf:"bytes,5,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentSvcLog) Reset()         { *m = PaymentSvcLog{} }
func (m *PaymentSvcLog) String() string { return proto.CompactTextString(m) }
func (*PaymentSvcLog) ProtoMessage()    {}
func (*PaymentSvcLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0530484c2e209d3, []int{0}
}

func (m *PaymentSvcLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentSvcLog.Unmarshal(m, b)
}
func (m *PaymentSvcLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentSvcLog.Marshal(b, m, deterministic)
}
func (m *PaymentSvcLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentSvcLog.Merge(m, src)
}
func (m *PaymentSvcLog) XXX_Size() int {
	return xxx_messageInfo_PaymentSvcLog.Size(m)
}
func (m *PaymentSvcLog) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentSvcLog.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentSvcLog proto.InternalMessageInfo

func (m *PaymentSvcLog) GetPaymentId() string {
	if m != nil {
		return m.PaymentId
	}
	return ""
}

func (m *PaymentSvcLog) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PaymentSvcLog) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *PaymentSvcLog) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *PaymentSvcLog) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func init() {
	proto.RegisterType((*PaymentSvcLog)(nil), "protologs.proto.protolog.PaymentSvcLog")
}

func init() { proto.RegisterFile("proto/protolog/paymentsvc.proto", fileDescriptor_f0530484c2e209d3) }

var fileDescriptor_f0530484c2e209d3 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x07, 0x93, 0x39, 0xf9, 0xe9, 0xfa, 0x05, 0x89, 0x95, 0xb9, 0xa9, 0x79, 0x25, 0xc5,
	0x65, 0xc9, 0x7a, 0x60, 0x31, 0x21, 0x09, 0x98, 0x54, 0x31, 0x44, 0x40, 0x0f, 0xc6, 0x57, 0x9a,
	0xc5, 0xc8, 0xc5, 0x1b, 0x00, 0x51, 0x1e, 0x5c, 0x96, 0xec, 0x93, 0x9f, 0x2e, 0x24, 0xcb, 0xc5,
	0x05, 0xd5, 0x1f, 0x9f, 0x99, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0xc4, 0x09, 0x15, 0xf1,
	0x4c, 0x11, 0x12, 0xe3, 0x62, 0x4b, 0xcc, 0xcd, 0x2f, 0xcd, 0x2b, 0x91, 0x60, 0x52, 0x60, 0xd4,
	0x60, 0x0e, 0x82, 0xf2, 0x84, 0xe4, 0xb9, 0xb8, 0x93, 0x4b, 0x8b, 0x4b, 0xf2, 0x73, 0x53, 0x8b,
	0x40, 0xfa, 0x98, 0xc1, 0xfa, 0xb8, 0x60, 0x42, 0x10, 0x8d, 0xb9, 0xa9, 0x25, 0x19, 0xf9, 0x29,
	0x12, 0x2c, 0x60, 0x39, 0x28, 0x4f, 0x48, 0x92, 0x8b, 0x23, 0xbf, 0x28, 0x05, 0xa2, 0x8b, 0x15,
	0x2c, 0xc3, 0x0e, 0xe6, 0x7b, 0xa6, 0x38, 0xd9, 0x72, 0xc9, 0x24, 0xe7, 0xe7, 0xea, 0xe1, 0x72,
	0xbc, 0x13, 0x7f, 0x00, 0xdc, 0xa3, 0x01, 0x20, 0xb1, 0x00, 0xc6, 0x28, 0x2e, 0x98, 0x64, 0x41,
	0x52, 0x12, 0x1b, 0x98, 0x6d, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x23, 0xfa, 0x88, 0x27, 0x1f,
	0x01, 0x00, 0x00,
}
