// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/protolog/paymentsvc.proto

package protolog

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	go_uber_org_zap_zapcore "go.uber.org/zap/zapcore"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (m *PaymentSvcLog) MarshalLogObject(enc go_uber_org_zap_zapcore.ObjectEncoder) error {
	var keyName string
	_ = keyName

	keyName = "payment_id" // field payment_id = 1
	enc.AddString(keyName, m.PaymentId)

	keyName = "amount" // field amount = 2
	enc.AddInt64(keyName, m.Amount)

	keyName = "customer_id" // field customer_id = 3
	enc.AddString(keyName, m.CustomerId)

	keyName = "method" // field method = 4
	enc.AddString(keyName, m.Method)

	keyName = "order_id" // field order_id = 5
	enc.AddString(keyName, m.OrderId)

	return nil
}
