// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/protolog/usersvc.proto

package protolog

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	go_uber_org_zap_zapcore "go.uber.org/zap/zapcore"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (m *UserSvcLog) MarshalLogObject(enc go_uber_org_zap_zapcore.ObjectEncoder) error {
	var keyName string
	_ = keyName

	keyName = "user_id" // field user_id = 1
	enc.AddString(keyName, m.UserId)

	keyName = "name" // field name = 2
	enc.AddString(keyName, m.Name)

	keyName = "errormsg" // field errormsg = 3
	enc.AddString(keyName, m.Errormsg)

	keyName = "city" // field city = 4
	enc.AddString(keyName, m.City)

	return nil
}
