// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/protolog/usersvc.proto

package protolog

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserSvcLog struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Errormsg             string   `protobuf:"bytes,3,opt,name=errormsg,proto3" json:"errormsg,omitempty"`
	City                 string   `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSvcLog) Reset()         { *m = UserSvcLog{} }
func (m *UserSvcLog) String() string { return proto.CompactTextString(m) }
func (*UserSvcLog) ProtoMessage()    {}
func (*UserSvcLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_d959dc161db323f5, []int{0}
}

func (m *UserSvcLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSvcLog.Unmarshal(m, b)
}
func (m *UserSvcLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSvcLog.Marshal(b, m, deterministic)
}
func (m *UserSvcLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSvcLog.Merge(m, src)
}
func (m *UserSvcLog) XXX_Size() int {
	return xxx_messageInfo_UserSvcLog.Size(m)
}
func (m *UserSvcLog) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSvcLog.DiscardUnknown(m)
}

var xxx_messageInfo_UserSvcLog proto.InternalMessageInfo

func (m *UserSvcLog) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserSvcLog) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserSvcLog) GetErrormsg() string {
	if m != nil {
		return m.Errormsg
	}
	return ""
}

func (m *UserSvcLog) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func init() {
	proto.RegisterType((*UserSvcLog)(nil), "protologs.proto.protolog.UserSvcLog")
}

func init() { proto.RegisterFile("proto/protolog/usersvc.proto", fileDescriptor_d959dc161db323f5) }

var fileDescriptor_d959dc161db323f5 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x07, 0x93, 0x39, 0xf9, 0xe9, 0xfa, 0xa5, 0xc5, 0xa9, 0x45, 0xc5, 0x65, 0xc9, 0x7a,
	0x60, 0x01, 0x21, 0x09, 0x98, 0x78, 0x31, 0x44, 0x40, 0x0f, 0xc6, 0x57, 0xca, 0xe4, 0xe2, 0x0a,
	0x2d, 0x4e, 0x2d, 0x0a, 0x2e, 0x4b, 0xf6, 0xc9, 0x4f, 0x17, 0x12, 0xe7, 0x62, 0x07, 0x69, 0x8c,
	0xcf, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0x03, 0x71, 0x3d, 0x53, 0x84, 0x84,
	0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x98, 0xc0, 0xa2, 0x60, 0xb6, 0x90, 0x14, 0x17, 0x47,
	0x6a, 0x51, 0x51, 0x7e, 0x51, 0x6e, 0x71, 0xba, 0x04, 0x33, 0x58, 0x1c, 0xce, 0x07, 0xa9, 0x4f,
	0xce, 0x2c, 0xa9, 0x94, 0x60, 0x81, 0xa8, 0x07, 0xb1, 0x9d, 0xac, 0xb8, 0x64, 0x92, 0xf3, 0x73,
	0xf5, 0x70, 0x39, 0xc5, 0x89, 0x27, 0x14, 0xe2, 0xe6, 0x00, 0x90, 0x40, 0x00, 0x63, 0x14, 0x17,
	0x4c, 0xa6, 0x20, 0x29, 0x89, 0x0d, 0xcc, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x98, 0x0c,
	0x6f, 0xe1, 0xe7, 0x00, 0x00, 0x00,
}
